# Generated by Django 4.0.4 on 2022-07-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficulty',
            new_name='difficluty',
        ),
    ]
